# Generated by Django 3.1.5 on 2022-05-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='auth_status',
        ),
        migrations.AddField(
            model_name='author',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='designation',
            field=models.CharField(choices=[('editor', 'editor'), ('author', 'author')], default='author', max_length=20),
        ),
    ]
