# Generated by Django 3.1.5 on 2022-05-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220527_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
