# Generated by Django 3.1.5 on 2022-05-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_author_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
