# Generated by Django 3.1.5 on 2022-05-15 12:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detail',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
