# Generated by Django 3.1.5 on 2022-05-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20220515_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='catagories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='cover_image',
        ),
    ]
